### ISSUE TITLE
Overwritten array entries in csp-parser-enhanced.php

### ISSUE THREAD

**Issue by endelwar** [nico3333fr/CSP-useful#22]
$tab_filter in csp-parser-enhanced.php contains a couple of entry that will never be triggered in foreach loop:
- 'chromenull://': 'filter_on' => 'source_file' is overwritten by  'chromenull://' 'filter_on' => 'blocked_uri'
- 'safari-extension://' 'filter_on' => 'blocked_uri' is overwritten by 'safari-extension://' 'filter_on' => 'source_file'

**Comment by nico3333fr** [comment]
Are you sure ?

The script makes a check on the entire array :

```
  // now perform checks on all element in array => filtering CSP noise
  foreach ( $tab_filter as $filter_check => $options ) {
    
      switch ($options['filter_on']) {
        case 'source_file':
            $filter_on = $data['csp-report']['source-file'];
            break;
        case 'blocked_uri':
            $filter_on = $data['csp-report']['blocked-uri'];
            break;
        case 'script_sample':
            $filter_on = $data['csp-report']['script-sample'];
            break;
        case 'referrer':
            $filter_on = $data['csp-report']['referrer'];
            break;
        case 'doc_uri':
            $filter_on = $data['csp-report']['document-uri'];
            break;
      }
      
      if ( strpos($filter_on, $filter_check) !== false ){
         $report_issue = false;
         break;
         }
    
    }
```

for each entry, it checks on the "filter on", and once it found a positive, it breaks the loop and doesn't send anything.

**Comment by endelwar** [comment]
Yes, the array index is overwritten: look at this https://3v4l.org/jXWBZ

**Comment by nico3333fr** [comment]
Yes, I didn't understand! It is fixed, a temporary fix while waiting to find a more elegant one. :)

Thanks a lot for pointing this out 👍
