### ISSUE TITLE
Explanation for https://sxt.cdn.skype.com/assets/fonts/SkypeAssets-Light.ttf

### ISSUE THREAD

**Issue by lol768** [nico3333fr/CSP-useful#27]
It's this: https://chrome.google.com/webstore/detail/skype/lifbcibllhkdhoafpjfnlhfpfgnpldfl

Trying to find an email address to tell them their extension is broken.

**Comment by jedi58** [comment]
https://go.skype.com/help.support.selection

**Comment by lol768** [comment]
Can't use that without a Skype account.

**Comment by jedi58** [comment]
If you've got a hotmail or other Microsoft account then it should work for Skype as well

**Comment by nico3333fr** [comment]
Hi there,

thanks a lot for this explanation, I've move the entry to explained section with https://github.com/nico3333fr/CSP-useful/commit/a0dc881af0cad42d0881a7c8ae065a4fc6f24672 .

Cheers 👍
