### ISSUE TITLE
root .mod > ._jH + .rscontainer???

### ISSUE THREAD

**Issue by 3ventic** [nico3333fr/CSP-useful#29]
https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#root-mod--_jh--rscontainer

Comes from https://easylist-downloads.adblockplus.org/easylist.txt (`##.mod > ._jH + .rscontainer` in the middle) and some ad blocking extensions [like uBlock Origin](https://github.com/gorhill/uBlock/issues/327) add the CSS in a <style> tag on the web page.

**Comment by nico3333fr** [comment]
Thanks for this. Would you mind if I mention it in the repo, and your help of course ?

**Comment by 3ventic** [comment]
Feel free :)

--
Werner V

**Comment by nico3333fr** [comment]
Done here https://github.com/nico3333fr/CSP-useful/commit/27503b74cb49f5a12d4b405eabac99a6165dd4b8 

Thanks a lot 👍
