### ISSUE TITLE
CSP wtf : chrome://kango-…

### ISSUE THREAD

**Issue by ryuran** [nico3333fr/CSP-useful#32]
https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#chromekango

Kango seems to be a firefox extension framework.
It can be from an extension using this framework.

http://kangoextensions.com/kango.html

**Comment by zero-24** [comment]
@ryuran I have created a PR that adds the possibe description to the doc: https://github.com/nico3333fr/CSP-useful/pull/34 👍

**Comment by nico3333fr** [comment]
Both of you are great, I've merged the PR 👍
