### ISSUE TITLE
mx://res/reader-mode/reader.html

### ISSUE THREAD

**Issue by ngyikp** [nico3333fr/CSP-useful#36]
This comes from the Reader Mode in Maxthon browser: http://wiki.maxthon.com/index.php/Maxthon_3_-_Reader_Mode

On old versions of Maxthon, a very strict CSP could also block Reader Mode entirely, but it has been fixed on the newer versions

**Comment by nico3333fr** [comment]
Thanks a lot, I've updated the repo in https://github.com/nico3333fr/CSP-useful/commit/c98898b51e63d90f155fdf66aa163cad03b9b222 

Thanks again for your help 👍
