### ISSUE TITLE
cip-genpw-icon

### ISSUE THREAD

**Issue by parseword** [nico3333fr/CSP-useful#40]
Hi,

It looks like the [cip-genpw-icon](https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#cip-genpw-icon) is coming from a browser extension called [ChromeIPass](https://github.com/pfn/passifox/blob/master/chromeipass/chromeipass.css#L45) and/or its Firefox counterpart PassIFox.

**Comment by nico3333fr** [comment]
Hi,

I've updated it, thanks a lot for your help 👍
