### ISSUE TITLE
wrcx source found?

### ISSUE THREAD

**Issue by IanOliver** [nico3333fr/CSP-useful#42]
Hey guys. Not sure if you wanted reports as issues (sorry if not!), but I believe I may have found the source of the unknown 'wrcx' report:

https://github.com/vikeshkhanna/pointers/blob/master/youtube_files/iframe.htm

It's a Chrome extension 'to add seek markers / pointers to the YouTube timeline. You can add as many pointers you wish, drag them on the timeline, delete them and seek to that point in the video by clicking the marker. Extension uses content scripts, jquery and jquery-ui. ' - see https://github.com/vikeshkhanna/pointers

**Comment by nico3333fr** [comment]
Hi @IanOliver 

you did well, thank you. I've updated the repo with this information https://github.com/nico3333fr/CSP-useful/commit/6cf6ae5fc09911f07b5c084f6fa432a8389d5ab2 👍 

Thanks a lot! :)
