### ISSUE TITLE
Why you should use CSP ?

### ISSUE THREAD

**Issue by dhoko** [nico3333fr/CSP-useful#43]
2 liens en plus pour la liste ;)

https://twitter.com/Scott_Helme/status/961612668992966656
https://scotthelme.co.uk/protect-site-from-cryptojacking-csp-sri/

**Comment by nico3333fr** [comment]
Merci, ajoutés : https://github.com/nico3333fr/CSP-useful/commit/05cd482fd124cb46bc0efa4963315f6d0ff0bd38 :)
