### ISSUE TITLE
Loop11

### ISSUE THREAD

**Issue by eternalmatt** [nico3333fr/CSP-useful#62]
https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#windowloop11extterritory--true

This is somehow related to "Loop11 User Testing"
- http://www.loop11.com/
- https://chrome.google.com/webstore/detail/loop11-user-testing/bhopfldlicecjkdoidhjfkhbndcjfomf?hl=en-US

**Comment by nico3333fr** [comment]
Thanks a lot, I've updated it https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/explained.md ;)

Cheers 👍
