### ISSUE TITLE
Explained: extension schemes

### ISSUE THREAD

**Issue by Zenexer** [nico3333fr/CSP-useful#70]
* https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#chrome-extension
* https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#chrome-extension-1
* https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#moz-extension
* https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#aboutblank

`chrome-extension:` will appear in reports when a Chrome extension attempts to inject a script, iframe, or other content into a page that doesn't explicitly allow the `chrome-extension:` scheme.  If users are complaining that their extensions aren't working on your site, this is why.  Oftentimes they're injecting questionable content (e.g., ads or analytics), in which case you may want to deliberately omit this.

`moz-extension` is the same thing, but for Firefox.

Depending on how the extension works and what browser is being used, `about:blank` or other `about:` URLs may appear instead of an extension scheme.

**Comment by nico3333fr** [comment]
Thanks a lot ;)
