### ISSUE TITLE
Remove misconfigured WTFs

### ISSUE THREAD

**Issue by Zenexer** [nico3333fr/CSP-useful#71]
Many of the WTFs are just the result of misconfigured CSP directives.  For example:

* https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#many-css-class-names-in-this-file
* https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#arelnofollow

Those are both lacking `'self'` for `style-src`, so their styles are getting blocked.

A good chunk of the `script-sample` entries fall into this category.  **Anything with `blocked-uri: self` should be considered to be a misconfiguration--the developer is simply missing `'self'`.**

**Comment by nico3333fr** [comment]
No, these styles are not present on the website and `self` is defined in CSP headers.

**Comment by MaceWindu** [comment]
actually first one is probably from this extension https://github.com/daidaiworm/vimium 

see this file https://searchcode.com/codesearch/view/26916074/

**Comment by MaceWindu** [comment]
Looking at second one I suspect it is also some SEO/malware extension to spam forums with SEO links as this snippet could be found alot on different message boards and it it adds extra styles to seo-related links.

**Comment by MaceWindu** [comment]
Close as explained?

**Comment by nico3333fr** [comment]
@MaceWindu yes, closed :)
