### ISSUE TITLE
Explained: uc.gre

### ISSUE THREAD

**Issue by Zenexer** [nico3333fr/CSP-useful#72]
https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/not-explained.md#httpucgrepass

This is most likely a result of content injected by UC Browser.  It's a popular browser in China and a few other countries in the region.  It seems to have a habit of siphoning data from web pages that its users visit, as well as injecting analytics and possibly ads.  This particular report may actually be from an extension designed for UC Browser.

**Comment by nico3333fr** [comment]
Thanks again ;)
