### ISSUE TITLE
Function break CSP checks

### ISSUE THREAD

**Issue by menocomp** [nico3333fr/CSP-useful#85]
The code base is still using `Function('return this');`

The latest version for ES6 is fine:
https://unpkg.com/pdfjs-dist@2.4.456/build/pdf.js

However it is still there for ES5 build:
https://unpkg.com/pdfjs-dist@2.4.456/es5/build/pdf.js

I do not want to allow `script-src 'eval'` in my CSP provider.

Is there any plan to fix ES5 build?

**Comment by menocomp** [comment]
Sorry I created this ticket in this repo by mistake :)

**Comment by nico3333fr** [comment]
@menocomp no problem ;)
